#!/bin/bash
# Bundle relay/src into one ES module and embed it in the app as generated
# Swift, so Settings can deploy the Worker without node on the user's
# machine. Dev-side only — requires relay/node_modules (npm install).
# The committed output is guarded by RelayWorkerDistTests.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$HERE/relay"
[ -x node_modules/.bin/esbuild ] || { echo "run npm install in relay/ first" >&2; exit 1; }

JS="$(node_modules/.bin/esbuild src/index.ts --bundle --format=esm --minify \
      --target=es2022 --external:cloudflare:workers)"
HASH="$(cat src/classify.ts src/env.d.ts src/index.ts src/relay-do.ts | shasum -a 256 | cut -d' ' -f1)"

OUT="$HERE/Sources/ClaudeStatusLight/RelayWorkerDist.swift"
{
    printf '// Generated by scripts/build-relay-dist.sh — DO NOT EDIT.\n'
    printf '// Regenerate after changing relay/src (RelayWorkerDistTests enforces this).\n\n'
    printf 'enum RelayWorkerDist {\n'
    printf '    static let sourceHash = "%s"\n' "$HASH"
    printf '    static let moduleJS = ##"""\n%s\n"""##\n' "$JS"
    printf '}\n'
} > "$OUT"
echo "wrote $OUT (source hash $HASH)"
